### PR TITLE
fix: truncate outer context lines

### LINKED ISSUE #121: Show inner context instead of outer
A while ago and in the gif inside the readme, this plugin used to show the inner context when `max_lines` was set. Now for some reason in all the languages I've tested (`rust`, `lua`, `java`), the outer one is shown.

For example:
```rust
impl A {
    fn b(&self) {
        ...
    }
}
```
When inside the function `b`, the context shown is `impl A {` instead of `fn b(&self) {`

Was this change intentional? And if it is, could we add a config option to switch to the old behavior?

### PR DESCRIPTION
**Pull request by Saecki**
Fixes #121, by restoring the previous behavior.

### CODE REVIEW

File: lua/treesitter-context.lua [hunk 1]
```diff
@@ -352,8 +340,7 @@ local function get_parent_matches(max_lines)
     node = node:parent()
   end
 
-  for i = #parents, 1, -1 do
-    local parent = parents[i]
+  for _,parent in ipairs(parents) do
```
Comment (romgrk) [inline lua/treesitter-context.lua:343]: Space after comma.

**Comment by romgrk** [comment]
LGTM, fix the linting issue and we can merge.

File: lua/treesitter-context.lua (hunk 1 above)
Comment (Saecki) [reply lua/treesitter-context.lua]: Done
