### PR TITLE
fix: restore line_numbers & more

### LINKED ISSUE #136: Documentation `line_numbers`
README mentions a `line_numbers` option at the end, but there's no other reference to it. Possibly an undocumented option?

### PR DESCRIPTION
**Pull request by romgrk**
Closes #136 

Seems like we already have the `line_numbers` code, but a few lines were missing. Also included fixes for an spurious error message on nvim exit.

### CODE REVIEW

File: lua/treesitter-context.lua [hunk 1]
```diff
@@ -576,7 +579,7 @@ local function open(ctx_nodes)
 
   local gbufnr, ctx_bufnr = get_bufs()
 
-  if vim.wo.number or vim.wo.relativenumber then
+  if config.line_numbers == true and (vim.wo.number or vim.wo.relativenumber) then
```
Comment (lewis6991) [inline lua/treesitter-context.lua:582]: I'd remove the `== true`, unless there's a reason you added it.

File: lua/treesitter-context.lua [hunk 2]
```diff
@@ -13,12 +13,12 @@ end
 local defaultConfig = {
   enable = true,
   max_lines = 0, -- no limit
+  line_numbers = false,
```
Comment (lewis6991) [inline lua/treesitter-context.lua:16]: Shouldn't we default this to `true`?

Comment (romgrk) [reply lua/treesitter-context.lua]: Ok sure

**Review by lewis6991 — APPROVED** [review]
