### PR TITLE
fix: Always call parse on the treesitter parser

### LINKED ISSUE #573: The context isn't shown unless `:InspectTree` is open
### Description

I'm opening a somewhat big python file (2.3k lines) and the cursor jumps directly to a big function (50 lines or so).

The context does not appear on the top of the window. In order to check if treesitter was able to operate on the file, I launched `:InspectTree` and voilà: the context appeared on the top of the window. If I close the treesitter window, the context is present and correctly updated.

### Neovim version

0.11.0

### Expected behavior

I would expect the context window to appear even without calling `:InspectTree`.

### Actual behavior

No context window appears unless `:InspectTree` is called.

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. `:TSInstall python`
3. Open a python file → No context window
4. `:InspectTree`
5. The context window appears

### PR DESCRIPTION
**Pull request by nicoe**
This should fix #573

### CODE REVIEW

**Comment by nicoe** [comment]
I wonder if the call to parse should be done on the root parser or on all the parsers. I must say that I seldomly use multiple language in the same buffer so I never tested this case.

File: lua/treesitter-context/context.lua [hunk 1]
```diff
@@ -215,6 +215,7 @@ local function get_parent_langtrees(bufnr, range)
     return {}
   end
 
+  root_tree:parse(range)
```
Comment (lewis6991) [inline lua/treesitter-context/context.lua:218]: Parsing can be async now, so this will have a perf hit.

Maybe we could try and pass an empty `on_parse` param.

File: lua/treesitter-context/context.lua [hunk 2]
```diff
@@ -215,6 +215,11 @@ local function get_parent_langtrees(bufnr, range)
     return {}
   end
 
+  if vim.version.ge(vim.version(), {0, 11, 0}) then
+    root_tree:parse(range, function(...) end)
+  else
+    root_tree:parse(range)
+  end
```
Comment (lewis6991) [inline lua/treesitter-context/context.lua:222]: This won't work. You just need to include the correct `@diagnostic: disable-next-line` annotation.

**Comment by nicoe** [comment]
I think the issue on luals is a false positive because it checks with nvim version 0.10 and does not take into account the version check before the code.

**Review by lewis6991 — CHANGES_REQUESTED** [review]
Can you provide a more detailed commit message please.

**Comment by nicoe** [comment]
> Can you provide a more detailed commit message please.

I hope it's OK for you
