### PR TITLE
Check if buffer is loaded

### LINKED ISSUE #455: Regression: some other things are broken at startup with `syntax on`
### Description

I noticed some things such as treesitter syntax highlighting and .editorconfig weren't applying at startup (when passing files as arguments to nvim).

I tracked the culprit down to this plugin and bisected the issue. The problematic commit is https://github.com/nvim-treesitter/nvim-treesitter-context/commit/2484f58384be24da375558c88402f2998193eff6. It seems reverting the function `M.get()` in that file fixes it.

### Neovim version

0.9.5 and 0.10.0

### Expected behavior

_No response_

### Actual behavior

Things break on first read from command line.

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE

vim.cmd [[syntax on]]
require("treesitter-context").setup {
}
```

### Steps to reproduce

An easy way to repro is to have a .editorconfig file like this:
```editorconfig
root = true

[*]
max_line_length = 99
```

Open a file like `nvim foo.c`, and run `:set tw?`. With ts-context enabled, this returns 0, while without it returns 99 as expected.

This doesn't repro when reading files with `:e`.

### PR DESCRIPTION
**Pull request by 9ary**
Fixes #455.

### CODE REVIEW

File: lua/treesitter-context/context.lua [hunk 1]
```diff
@@ -253,6 +253,14 @@ end
 --- @param winid integer
 --- @return Range4[]?, string[]?
 function M.get(bufnr, winid)
+  -- vim.treesitter.get_parser() calls bufload(), but we don't actually want to load the buffer:
+  -- this method is called during plugin init, before other plugins or the user's config
+  -- have a chance to initialize.
+  -- They may want to register autocmds, and this would prevent them from firing.
+  if vim.fn.bufloaded(bufnr) == 0 then
```
Comment (bb010g) [inline lua/treesitter-context/context.lua:260]: Prefer [nvim_buf_is_loaded\(\)](https://neovim.io/doc/user/api.html#nvim_buf_is_loaded()>) from Lua code.

File: lua/treesitter-context/context.lua [hunk 2]
```diff
@@ -253,6 +253,14 @@ end
 --- @param winid integer
 --- @return Range4[]?, string[]?
 function M.get(bufnr, winid)
+  -- vim.treesitter.get_parser() calls bufload(), but we don't actually want to load the buffer:
+  -- this method is called during plugin init, before other plugins or the user's config
+  -- have a chance to initialize.
+  -- They may want to register autocmds, and this would prevent them from firing.
+  if not vim.api.nvim_buf_is_loaded(bufnr) then
```
Comment (lewis6991) [inline lua/treesitter-context/context.lua:260]:
```suggestion
  if not api.nvim_buf_is_loaded(bufnr) then
```
