### PR TITLE
fix(nighly): use get_hl_from_capture for nightly, instead of hl_cache

### LINKED ISSUE #387: Context has no highlighting when first opening Neovim
### Description

If I open Neovim in a way that the context window is already open, then the context content has no highlighting until the context window is closed at least once.

### Neovim version

v0.10.0-dev-2257+g302fa5f7d

### Expected behavior

For the context window to always have the expected highlighting.

### Actual behavior

This is what it looks like the first time:
20240205_13h26m03s_grim

### Minimal config

```Lua
local plugins = {
  ts = "https://github.com/nvim-treesitter/nvim-treesitter",
  ts_context = "https://github.com/nvim-treesitter/nvim-treesitter-context",
  tokyo_night = "https://github.com/folke/tokyonight.nvim",
}

for name, url in pairs(plugins) do
  local install_path = "nvim_issue/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { "git", "clone", "--depth=1", url, install_path }
  end
  vim.o.runtimepath = install_path .. "," .. vim.o.runtimepath
end

vim.cmd [[colorscheme tokyonight]]

require("tokyonight").setup()
require("nvim-treesitter.configs").setup { ensure_installed = { "lua" } }
require("treesitter-context").setup()

local foo = {
  bar = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "fish",
      "gitcommit",
      "javascript",
      "json",
      "json5",
      "jsonc",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "rust",
      "scss",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
      "bash",
      "c",
      "cpp",
      "fish",
      "gitcommit",
      "javascript",
      "json",
      "json5",
      "jsonc",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "rust",
      "scss",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
    },
  },
}
```

### Steps to reproduce

1. Include the above configuration file in `minimal.lua`.
2. Open Neovim with `nvim --clean -u minimal.lua minimal.lua -c "normal50Gzz"`.
3. Notice how the context window has no colorization. Then run `gg50Gzz` and notice how the context window is now highlighted.

### PR DESCRIPTION
**Pull request by Sam-programs**
Seems to Fix #387

https://github.com/nvim-treesitter/nvim-treesitter-context/assets/130783534/fa4add42-52c1-48b1-8986-2eb961ae2dd6

Stable works fine without this.

### CODE REVIEW

**Review by romgrk — APPROVED** [review]

File: lua/treesitter-context/render.lua [hunk 1]
```diff
@@ -150,8 +150,12 @@ local function highlight_contexts(bufnr, ctx_bufnr, contexts)
         if nsrow >= start_row then
           local msrow = offset + (nsrow - start_row)
           local merow = offset + (nerow - start_row)
-
-          local hl = buf_query.hl_cache[capture]
+          local hl --- @type integer
+          if buf_query.get_hl_from_capture then
```
Comment (lewis6991) [inline lua/treesitter-context/render.lua:154]: Is this not always defined?

Comment (romgrk) [reply lua/treesitter-context/render.lua:154]: It would be undefined on older neovim versions.

Comment (lewis6991) [reply lua/treesitter-context/render.lua:154]: Which versions? We only target the latest release.

Comment (romgrk) [reply lua/treesitter-context/render.lua:154]: I think not breaking older versions is nice, it can be refactored later. In my other plugins I usually try to have them working on whatever debian/ubuntu stable has, which is 0.7 at the moment.

Comment (lewis6991) [reply lua/treesitter-context/render.lua:154]: Not for a treesitter plugin. Even for Neovim core, treesitter is still considered experimental and the API's are moving quickly.

We can keep this as is, but just note going forward, backwards compatibility is a non-goal.

Comment (Not-a-ghost1) [reply lua/treesitter-context/render.lua:154]: Hi. I have lost access to my account @Sam-programs.

 > Which versions? We only target the latest release.

The function isn't defined in stable, tag latest in the releases page.
